export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2 style= {{background:"brown"}}>This is the Header.</h2>
        </header>
        {children}
      </body>
    </html>
  )
}
