export const metadata = {
  title:{
    default: "CodeEvolution Coding",
    template:"%s | CodeEvolution ",
    absolute:"" 
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
